CREATE TABLE IF NOT EXISTS user (
    login VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS like (
    id SERIAL PRIMARY KEY,
    cat_id VARCHAR(50) NOT NULL,
    cat_url VARCHAR(255) NOT NULL,
    user_login VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
)
